server:
  #服务端口
  port: 9100 

spring: 
  application: 
    #指定服务名 
    name: binghe-eureka-provider 

eureka:
  client:
    #是否将自己注册到Eureka服务中
    registerWithEureka: true 
    #是否从Eureka中获取注册信息
    fetchRegistry: true 
    serviceUrl: 
      #Eureka客户端与Eureka服务端进行交互的地址（往有登陆权限的注册中心注册服务需要在IP前面加上user:password@）
      defaultZone: http://binghe:binghe@127.0.0.1:6868/eureka/,http://bingyu:bingyu@127.0.0.1:6869/eureka/
  instance: 
    #将自己的ip地址注册到Eureka服务中
    prefer-ip-address: true 
    ip-address: 127.0.0.1
