server:
  #服务端口
  port: 6677 

spring: 
  application: 
    #指定服务名 
    name: binghe-eureka-zuul

eureka:
  client:
    #是否将自己注册到Eureka服务中
    registerWithEureka: true 
    #是否从Eureka中获取注册信息
    fetchRegistry: true 
    serviceUrl: 
      #Eureka客户端与Eureka服务端进行交互的地址（往有登陆权限的注册中心注册服务需要在IP前面加上user:password@）
      defaultZone: http://binghe:binghe@127.0.0.1:6868/eureka/,http://bingyu:bingyu@127.0.0.1:6869/eureka/
  instance: 
    #将自己的ip地址注册到Eureka服务中
    prefer-ip-address: true 
    ip-address: 127.0.0.1
    
#zuul: 
#  #使用'*'可忽略所有微服务，如果要忽略指定的微服务则写下对应服务的servicesId，有多个用逗号隔开
##  ignored-services: '*'
#  routes: 
#    #binghe-eureka-consumer为指定服务的id。访问 /consumer-service/** 的请求会被重定向到 binghe-eureka-consumer 服务对应的url
#    binghe-eureka-consumer: /consumer-service/**

